{
    "name": "Remote Schema",
    "schemaPath": "schema.graphql",
    "extensions": {
        "endpoints": {
            "PWA Test": {
                "url": "https://pwa-test.local.pwadev:8525/",
                "headers": {
                    "user-agent": "JS GraphQL"
                },
                "introspect": true
            }
        }
    }
}
